services:
  db:
    image: postgres:18
    environment:
      POSTGRES_PASSWORD: postgres
    ports: ["5432:5432"]

  app:
    build: .
    volumes: [".:/app"]
    ports: ["4000:4000"]
    depends_on: [db]
    environment:
      DATABASE_URL: ecto://postgres:postgres@db/app_dev
    stdin_open: true
    tty: true